name: ci

on:
  release:
    types: [ created ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Restore .NET dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build --no-restore -c Release \
            -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} \
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install spice2json
        run: go install github.com/alsbury/spice2json@latest
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'created'
        run: dotnet nuget push src/SpiceWeaver/bin/Release/${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
