name: ci

on:
  push:
    branches: [ "main" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      CONFIGURATION: Release
      SPICE2JSON_VERSION: 0.3.4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Restore .NET dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build --no-restore -c ${{ env.CONFIGURATION }} \
            -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} \
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - name: Setup spice2json
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/alsbury/spice2json/releases/download/v${{ env.SPICE2JSON_VERSION }}/spice2json-v${{ env.SPICE2JSON_VERSION }}-linux-amd64.tar.gz'
          name: 'spice2json'
          version: '${{ env.SPICE2JSON_VERSION }}'
      - name: Test
        run: dotnet test --no-build --verbosity normal -c ${{ env.CONFIGURATION }}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push src/SpiceWeaver/bin/Release/SpiceWeaver.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            src/SpiceWeaver/bin/Release/SpiceWeaver.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg
